### ISSUE TITLE
document copy button plugin

### ISSUE THREAD

**Issue by o-az** [rehype-pretty/rehype-pretty-code#208]

**Comment by bennycode** [comment]
Hello, I was searching on how to add a copy-to-clipboard button using rehype-pretty-code in my Astro blog. Fortunately, I stumbled upon some clues in your code:

```md
## Available Transformers

- [`transformerCopyButton`](./src/copy-button.ts)
```

To make it work, I've included `@rehype-pretty/transformers` in my project:

```bash
npm i @rehype-pretty/transformers
```

Afterward, I updated the options in my `astro.config.ts` file:

```ts
import rehypePrettyCode, { type LineElement, type Options } from 'rehype-pretty-code';
import { transformerCopyButton } from '@rehype-pretty/transformers'

// ...

const rehypePrettyCodeOptions: Options = {
  theme: 'github-dark-dimmed',
  onVisitLine(node: LineElement) {
    // Prevent lines from collapsing in `display: grid` mode, and
    // allow empty lines to be copy/pasted
    if (node.children.length === 0) {
      node.children = [
        {
          type: 'text',
          value: ' ',
        },
      ];
    }
  },
  tokensMap: {
    fn: 'entity.name.function',
  },
  transformers: [
    transformerCopyButton({
      visibility: 'always',
      feedbackDuration: 3_000,
    }),
  ]
};

// ...

export default defineConfig({
  // https://docs.astro.build/en/guides/markdown-content/#markdown-plugins
  markdown: {
    // Disable automatic apostrophe generation: https://daringfireball.net/projects/smartypants/
    smartypants: false,
    syntaxHighlight: false,
    remarkPlugins: [remarkToc, remarkHexo],
    rehypePlugins: [[rehypePrettyCode, rehypePrettyCodeOptions]],
  },
  // ...
});
```  

The results look amazing!

Thank you very much,
Benny

**Comment by bennycode** [comment]
@o-az I noticed that the "copy" button shows fine in my local deployment but it doesn't show in my live deployment although the copy button fragment is present (tested with `document.querySelector('.rehype-pretty-copy');`). Do you know what could be the reason of it?

Here is my live deployment which should show the button: https://typescript.tv/hands-on/all-you-need-to-know-about-iterators-and-generators/

**Comment by nebrelbug** [comment]
Btw, the copy plugin seems to be broken for me.

**Comment by o-az** [comment]
> Btw, the copy plugin seems to be broken for me.

got a reporo?

**Comment by o-az** [comment]
@bennycode glad you were able to set it up! Updated docs should be out very soon :)

**Comment by o-az** [comment]
new docs are finally in a decent-enough place. Publishing soon

**Comment by udohjeremiah** [comment]
The copy button for Next.js fails with the typical text doesn't match server rendered.

**Comment by Flysky12138** [comment]
I get a error for Next.js

```ini
Error: Expected `onClick` listener to be a function, instead got a value of `string` type.
```

**Comment by ViniciusCestarii** [comment]
I got a workaround to make this work on Next.js and prevent hydration error.

I looked at the library code  and moved the parts where the hydration error occured.

```js
function transformerCopyButton() {
  return {
    name: '@rehype-pretty/transformers/copy-button',
    code(node) {
      node.children.push({
        type: 'element',
        tagName: 'button',
        properties: {
          type: 'button',
          title: 'Copy code',
          'aria-label': 'Copy code',
          data: this.source,
          class: 'rehype-pretty-copy',
        },
        children: [
          {
            type: 'element',
            tagName: 'svg',
            properties: {
              xmlns: 'http://www.w3.org/2000/svg',
              width: 24,
              height: 24,
              viewBox: '0 0 24 24',
              fill: 'none',
              stroke: 'currentColor',
              strokeWidth: 2,
              strokeLinecap: 'round',
              strokeLinejoin: 'round',
              class: 'lucide lucide-copy ready',
            },
            children: [
              {
                type: 'element',
                tagName: 'rect',
                properties: {
                  width: 14,
                  height: 14,
                  x: 8,
                  y: 8,
                  rx: 2,
                  ry: 2,
                },
                children: [],
              },
              {
                type: 'element',
                tagName: 'path',
                properties: {
                  d: 'M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2',
                },
                children: [],
              },
            ],
          },
          {
            type: 'element',
            tagName: 'svg',
            properties: {
              xmlns: 'http://www.w3.org/2000/svg',
              width: 24,
              height: 24,
              viewBox: '0 0 24 24',
              fill: 'none',
              stroke: 'currentColor',
              strokeWidth: 2,
              strokeLinecap: 'round',
              strokeLinejoin: 'round',
              class: 'lucide lucide-check success',
            },
            children: [
              {
                type: 'element',
                tagName: 'path',
                properties: {
                  d: 'M20 6 9 17l-5-5',
                },
                children: [],
              },
            ],
          },
        ],
      })
    },
  }
}
```

to add the behavior i created this js script 

```js
const copyButtons = document.querySelectorAll('.rehype-pretty-copy')

copyButtons.forEach((button) => {
  console.log(button)
  button.onclick = function () {
    navigator.clipboard.writeText(this.getAttribute('data'))

    this.classList.add('rehype-pretty-copied')

    window.setTimeout(() => {
      this.classList.remove('rehype-pretty-copied')
    }, 3000)
  }
})

```

then to add the behaviour to the button I added the script tag to my layout

```ts
import Script from 'next/script'

export default function PostLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Script src="/copy-button-behavior.js" />
      {children}
    </>
  )
}
```

then the styles i added into my global.css

```css
pre:has(code) {
  position: relative;
}

pre button.rehype-pretty-copy {
  right: 1px;
  padding: 0;
  background-color: hsl(var(--background));
  width: 2rem;
  padding: 0.25rem;
  aspect-ratio: 1 / 1;
  display: flex;
  margin-top: 2px;
  margin-right: 0.5rem;
  position: absolute;
  border-radius: var(--radius);
  backdrop-filter: blur(3px);
  & .ready { display: block; padding: 0.1rem; }
  & .success { display: none; }
}

&.rehype-pretty-copied { 
  & .success { 
    display: block;
  } & .ready {
    display: none;
  }
}
pre button.rehype-pretty-copy.rehype-pretty-copied {
  opacity: 1;
  & .ready { display: none; }
  & .success { display: block; }
}

/* show only on hover */
pre button.rehype-pretty-copy { opacity: 0; }
figure[data-rehype-pretty-code-figure]:hover > pre > code button.rehype-pretty-copy {
  opacity: 1;
}
```

the library @rehype-pretty/transformers isnt necessary for this code to work
